# Generated by Django 6.0.2 on 2026-02-07 15:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_uuid', models.CharField(help_text='Unique transaction ID generated for eSewa', max_length=255, unique=True)),
                ('esewa_transaction_code', models.CharField(blank=True, help_text='eSewa transaction code returned after payment', max_length=255, null=True)),
                ('esewa_refund_code', models.CharField(blank=True, help_text='eSewa refund code if payment was refunded', max_length=255, null=True)),
                ('product_code', models.CharField(default='BOOKINGFEE', help_text='Product code for eSewa', max_length=100)),
                ('signature', models.TextField(blank=True, help_text='Signature for payment verification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='bookings_pa_booking_bf00c8_idx'), models.Index(fields=['transaction_uuid'], name='bookings_pa_transac_512781_idx'), models.Index(fields=['created_at'], name='bookings_pa_created_0175e9_idx')],
            },
        ),
    ]
